const IMAGES = {
  LOAD: 'IMAGES_LOAD',
  LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
  LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

const STATS = {
  LOAD: 'STAT_LOAD',
  LOAD_SUCCESS: 'STAT_LOAD_SUCCESS',
  LOAD_FAIL: 'STAT_LOAD_FAIL',
};

export { IMAGES, STATS };
